== Check Garbage Collection ==

This section provides example configuration for collecting garbage collection statistics.

=== Installation: ===

Edit your commands.cfg and add the following

 define command {
    command_name    check_jboss_gc
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -g $ARG5$ -W $ARG6$ -C $ARG7$
 }

(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

=== Usage: ===

===== Check Minor GC Time =====

The option +gctime+ allows you to monitor the average minor garbage collection time in milliseconds.

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Avg. Minor GC time Check
    check_command           check_jboss_gc!gctime!9990!admin!password123!PS_Scavenge!50!100
 }

Sample output:

+OK - GC 'PS_Scavenge' collection-time 1776 collection-count 300 avg-time 5 |gctime=5;50;100 +

===== Check Major GC Time =====

The option +gctime+ allows you to monitor the average major garbage collection time in milliseconds.

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Percent GC time Check
    check_command           check_jboss_gc!gctime!9990!admin!password123!PS_MarkSweep!500!1000
 }

Sample output:

+OK - GC 'PS_MarkSweep' collection-time 468 collection-count 2 avg-time 234 |gctime=234;500;1000 +

