== Memory Usage ==

=== Installation: ===

Edit your commands.cfg and add the following

 define command {
    command_name    check_jboss_memory
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -W $ARG5$ -C $ARG6$
 }

(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

=== Usage: ===

===== Check Heap Memory Usage =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Heap Memory Usage Check
    check_command           check_jboss_memory!heap_usage!9990!admin!password123!80!90
 }

===== Check Non Heap Usage =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Non-Heap Memory Usage Check
    check_command           check_jboss_memory!non_heap_usage!9990!admin!password123!80!90
 }

===== Check Perm Gen Usage =====

===== Check Code Cache Usage =====

