== Nagios Plugin JBossAS7 ==

This project provides a Nagios plugin for JBossAS 7.1.1 resource monitoring. The plugin uses HTTP-JSON based API (JBossAS REST Management API) to collect server statistics. The plugin currently supports JBoss standalone mode.

Other plugins need additional +SAR+ or +WAR+ to be installed on the application server. Typically in Enterprise setups; it is sometimes not allowed to perform any additional installations on the target system.
The main advantage of this plugin is it leverages the +REST+ API of JBossAS. This allows us to monitor the application server without any additional configurations and installations.

link:#runtime[Server Status] :: Checks JBossAS status
link:memory.asciidoc[JVM Memory Utilization] :: Checks Heap, Non Heap, Old Gen, Eden Space, Perm Gen Utilization
link:#garbage-collection[Garbage Collection] :: Checks Garbage collection rate
link:#messaging[HornetQ Messaging] :: Checks message queue depths
link:datasource.asciidoc[DataSource Pool Usage] :: Checks datasource pool Utilization
link:#threading[Threading] :: Checks thread pool Utilization

=== Requirements: ===
* Nagios
* Python 2.7 onwards (with +requests+ module used for digest authentication)
* JBossAS 7.1.1-Final

=== Installation: ===

Edit your commands.cfg and add the following

 define command {
    command_name    check_jboss
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -W $ARG5$ -C $ARG6$
 }
 
 define command {
    command_name    check_jboss_gc
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -g $ARG5$ -W $ARG6$ -C $ARG7$
 }
 
 define command {
    command_name    check_jboss_messaging
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -q $ARG5$ -W $ARG6$ -C $ARG7$
 }

 define command {
    command_name    check_jboss_threading
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -t $ARG5$ -W $ARG6$ -C $ARG7$
 }
 
(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

=== Usage: ===

==== Runtime ====

===== Check Server State =====
 
 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Connectivity Check
    check_command           check_jboss!server_status!9990!admin!password123!!
 }

==== Garbage Collection ====

===== Check GC Time =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Percent GC time Check
    check_command           check_jboss_gc!gctime_percent!9990!admin!password123!gc_type!0.5!1.0
 }


==== Threading ====

===== Check thread count =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Threading thread count
    check_command           check_jboss_threading!threading!9990!admin!password123!thread-count
 }

===== Check daemon thread count =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Threading daemon thread count
    check_command           check_jboss_threading!threading!9990!admin!password123!daemon-thread-count
 }

===== Check total started thread count =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Threading total started thread count
    check_command           check_jboss_threading!threading!9990!admin!password123!total-started-thread-count
 }

==== Messaging ====

===== Check JMS Queue Depth =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Message queue depth
    check_command           check_jboss_messaging!queue_depth!9990!admin!password123!queue_name
 }

=== Licensing and Copyright: ===

The project is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
