== Nagios Plugin JBossAS7 ==

This project provides a Nagios plugin for JBossAS 7.1.1 resource monitoring. The plugin uses HTTP-JSON based API (JBossAS REST Management API) to collect server statistics.

=== How it works: ===


=== Requirements: ===
* Nagios
* Python
* JBossAS 7.1.1-Final

=== Installation: ===

Edit your commands.cfg and add the following

 define command {
    command_name    check_jboss
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -W $ARG5$ -C $ARG6$
 }
 
 define command {
    command_name    check_jboss_memory
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -m $ARG5$ -W $ARG6$ -C $ARG7$
 }

 define command {
    command_name    check_jboss_gc
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -g $ARG5$ -W $ARG6$ -C $ARG7$
 }
 
 define command {
    command_name    check_jboss_messaging
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -q $ARG5$ -W $ARG6$ -C $ARG7$
 }

 define command {
    command_name    check_jboss_datasource
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -d $ARG5$ -s $ARG6$ -W $ARG7$ -C $ARG8$
 }
 
(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

=== Usage: ===

==== General: ====

===== Check Server State =====
 
 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Connectivity Check
    check_command           check_jboss!server_status!9990!admin!password123!!
 }

==== JVM Monitoring ====


===== Check Heap Memory Usage =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Heap Memory Usage Check
    check_command           check_jboss_memory!heap_usage!9990!admin!password123!memory_type!512!1024
 }

===== Check Non Heap Usage =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Non-Heap Memory Usage Check
    check_command           check_jboss_memory!non_heap_usage!9990!admin!password123!memory_type!128!256
 }

===== Check GC Time =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Percent GC time Check
    check_command           check_jboss_gc!gctime_percent!9990!admin!password123!gc_type!0.5!1.0
 }


==== DataSource ====

Following statistics are supported:

.Table Datasource Monitoring Metrics
[cols="3*", options="header"]
|===
|Metric Type |Description |Unit

|ActiveCount
|The number of active connections. Each of the connections is either in use by an application or available in the pool.
|-

|AvailableCount
|TThe number of available connections in the pool
|-

|AverageBlockingTime
|The average time spent blocking on obtaining an exclusive lock on the pool.
|milliseconds

|AverageCreationTime
|The average time spent creating a connection.
|milliseconds

|CreatedCount
|The number of connections created
|-

|DestroyedCount
|The number of connections destroyed
|-

|MaxCreationTime
|The maximum time it took to create a connection.
|milliseconds

|MaxUsedCount
|The maximum number of connections used
|-

|MaxWaitTime
|The maximum time spent waiting for an exclusive lock on the pool
|milliseconds

|TimedOut
|The number of timed out connections
|milliseconds

|TotalBlockingTime
|The total time spent waiting for an exclusive lock on the pool.
|milliseconds

|TotalCreationTime
|The total time spent creating connections. 
|milliseconds

|===

===== Check Non-XA Datasource Active Connection Count =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Datasource active connection count
    check_command           check_jboss_datasource!datasource!9990!admin!password123!ds_name!ActiveCount
 }

===== Check Non-XA Datasource Average Blocking time =====

The average time spent blocking for a connection.

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Datasource average blocking time
    check_command           check_jboss_datasource!datasource!9990!admin!password123!ds_name!AverageBlockingTime
 }

===== Check XA Datasource Active Connection Count =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Datasource active connection count
    check_command           check_jboss_datasource!xa_datasource!9990!admin!password123!ds_name!ActiveCount
 }

==== Messaging ====

===== Check JMS Queue Depth =====

 define service {
    use                     generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Message queue depth
    check_command           check_jboss_messaging!queue_depth!9990!admin!password123!gc_type
 }

=== Licensing and Copyright: ===

The project is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
