== Nagios Plugin JBossAS7 ==

This project provides a Nagios plugin for JBossAS 7.1.1 resource monitoring. The plugin uses HTTP-JSON based API (JBossAS REST Management API) to collect server statistics.

=== Requirements: ===
* Nagios
* Python

=== Installation: ===

Edit your commands.cfg and add the following

 define command {
    command_name    check_jboss
    command_line    $USER1$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -u $ARG3$ -p $ARG4$ -W $ARG5$ -C $ARG6$
 }
 
 
(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

=== Usage: ===

==== General: ====

===== Check Server State =====

 
 define service {
    use                 generic-service
    hostgroup_name          JBossAS Servers
    service_description     JBossAS Server Connectivity Check
    check_command           check_jboss!server_status!9990!admin!password123!!
 }

==== [Purple]#JVM# ====

===== Check Heap Memory Usage =====

===== Check Non Heap Usage =====

===== Check GC Time =====


==== DataSource ====

===== Check Datasource Connection Count =====

==== Messaging ====

===== Check JMS Message Count =====

=== How it works: ===

=== Licensing and Copyright: ===

The project is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
